# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aurelienbrachet/Desktop/cpp/web-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aurelienbrachet/Desktop/cpp/web-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aurelienbrachet/Desktop/cpp/web-server/CMakeFiles /Users/aurelienbrachet/Desktop/cpp/web-server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aurelienbrachet/Desktop/cpp/web-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named web_server_lib

# Build rule for target.
web_server_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 web_server_lib
.PHONY : web_server_lib

# fast build rule for target.
web_server_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/build
.PHONY : web_server_lib/fast

#=============================================================================
# Target rules for targets named event_loop

# Build rule for target.
event_loop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 event_loop
.PHONY : event_loop

# fast build rule for target.
event_loop/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_loop.dir/build.make CMakeFiles/event_loop.dir/build
.PHONY : event_loop/fast

#=============================================================================
# Target rules for targets named web_server

# Build rule for target.
web_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 web_server
.PHONY : web_server

# fast build rule for target.
web_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server.dir/build.make CMakeFiles/web_server.dir/build
.PHONY : web_server/fast

#=============================================================================
# Target rules for targets named web_server_tests

# Build rule for target.
web_server_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 web_server_tests
.PHONY : web_server_tests

# fast build rule for target.
web_server_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/build
.PHONY : web_server_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server.dir/build.make CMakeFiles/web_server.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server.dir/build.make CMakeFiles/web_server.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server.dir/build.make CMakeFiles/web_server.dir/main.cpp.s
.PHONY : main.cpp.s

src/event_loop/event_loop_factory.o: src/event_loop/event_loop_factory.cpp.o
.PHONY : src/event_loop/event_loop_factory.o

# target to build an object file
src/event_loop/event_loop_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/event_loop/event_loop_factory.cpp.o
.PHONY : src/event_loop/event_loop_factory.cpp.o

src/event_loop/event_loop_factory.i: src/event_loop/event_loop_factory.cpp.i
.PHONY : src/event_loop/event_loop_factory.i

# target to preprocess a source file
src/event_loop/event_loop_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/event_loop/event_loop_factory.cpp.i
.PHONY : src/event_loop/event_loop_factory.cpp.i

src/event_loop/event_loop_factory.s: src/event_loop/event_loop_factory.cpp.s
.PHONY : src/event_loop/event_loop_factory.s

# target to generate assembly for a file
src/event_loop/event_loop_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/event_loop/event_loop_factory.cpp.s
.PHONY : src/event_loop/event_loop_factory.cpp.s

src/event_loop/macos_event_loop.o: src/event_loop/macos_event_loop.cpp.o
.PHONY : src/event_loop/macos_event_loop.o

# target to build an object file
src/event_loop/macos_event_loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_loop.dir/build.make CMakeFiles/event_loop.dir/src/event_loop/macos_event_loop.cpp.o
.PHONY : src/event_loop/macos_event_loop.cpp.o

src/event_loop/macos_event_loop.i: src/event_loop/macos_event_loop.cpp.i
.PHONY : src/event_loop/macos_event_loop.i

# target to preprocess a source file
src/event_loop/macos_event_loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_loop.dir/build.make CMakeFiles/event_loop.dir/src/event_loop/macos_event_loop.cpp.i
.PHONY : src/event_loop/macos_event_loop.cpp.i

src/event_loop/macos_event_loop.s: src/event_loop/macos_event_loop.cpp.s
.PHONY : src/event_loop/macos_event_loop.s

# target to generate assembly for a file
src/event_loop/macos_event_loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/event_loop.dir/build.make CMakeFiles/event_loop.dir/src/event_loop/macos_event_loop.cpp.s
.PHONY : src/event_loop/macos_event_loop.cpp.s

src/http/http_parser.o: src/http/http_parser.cpp.o
.PHONY : src/http/http_parser.o

# target to build an object file
src/http/http_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/http_parser.cpp.o
.PHONY : src/http/http_parser.cpp.o

src/http/http_parser.i: src/http/http_parser.cpp.i
.PHONY : src/http/http_parser.i

# target to preprocess a source file
src/http/http_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/http_parser.cpp.i
.PHONY : src/http/http_parser.cpp.i

src/http/http_parser.s: src/http/http_parser.cpp.s
.PHONY : src/http/http_parser.s

# target to generate assembly for a file
src/http/http_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/http_parser.cpp.s
.PHONY : src/http/http_parser.cpp.s

src/http/http_parser_test.o: src/http/http_parser_test.cpp.o
.PHONY : src/http/http_parser_test.o

# target to build an object file
src/http/http_parser_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/src/http/http_parser_test.cpp.o
.PHONY : src/http/http_parser_test.cpp.o

src/http/http_parser_test.i: src/http/http_parser_test.cpp.i
.PHONY : src/http/http_parser_test.i

# target to preprocess a source file
src/http/http_parser_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/src/http/http_parser_test.cpp.i
.PHONY : src/http/http_parser_test.cpp.i

src/http/http_parser_test.s: src/http/http_parser_test.cpp.s
.PHONY : src/http/http_parser_test.s

# target to generate assembly for a file
src/http/http_parser_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/src/http/http_parser_test.cpp.s
.PHONY : src/http/http_parser_test.cpp.s

src/http/request.o: src/http/request.cpp.o
.PHONY : src/http/request.o

# target to build an object file
src/http/request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/request.cpp.o
.PHONY : src/http/request.cpp.o

src/http/request.i: src/http/request.cpp.i
.PHONY : src/http/request.i

# target to preprocess a source file
src/http/request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/request.cpp.i
.PHONY : src/http/request.cpp.i

src/http/request.s: src/http/request.cpp.s
.PHONY : src/http/request.s

# target to generate assembly for a file
src/http/request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/request.cpp.s
.PHONY : src/http/request.cpp.s

src/http/response.o: src/http/response.cpp.o
.PHONY : src/http/response.o

# target to build an object file
src/http/response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/response.cpp.o
.PHONY : src/http/response.cpp.o

src/http/response.i: src/http/response.cpp.i
.PHONY : src/http/response.i

# target to preprocess a source file
src/http/response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/response.cpp.i
.PHONY : src/http/response.cpp.i

src/http/response.s: src/http/response.cpp.s
.PHONY : src/http/response.s

# target to generate assembly for a file
src/http/response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/response.cpp.s
.PHONY : src/http/response.cpp.s

src/http/routes_registery.o: src/http/routes_registery.cpp.o
.PHONY : src/http/routes_registery.o

# target to build an object file
src/http/routes_registery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/routes_registery.cpp.o
.PHONY : src/http/routes_registery.cpp.o

src/http/routes_registery.i: src/http/routes_registery.cpp.i
.PHONY : src/http/routes_registery.i

# target to preprocess a source file
src/http/routes_registery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/routes_registery.cpp.i
.PHONY : src/http/routes_registery.cpp.i

src/http/routes_registery.s: src/http/routes_registery.cpp.s
.PHONY : src/http/routes_registery.s

# target to generate assembly for a file
src/http/routes_registery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/http/routes_registery.cpp.s
.PHONY : src/http/routes_registery.cpp.s

src/http/routes_registery_test.o: src/http/routes_registery_test.cpp.o
.PHONY : src/http/routes_registery_test.o

# target to build an object file
src/http/routes_registery_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/src/http/routes_registery_test.cpp.o
.PHONY : src/http/routes_registery_test.cpp.o

src/http/routes_registery_test.i: src/http/routes_registery_test.cpp.i
.PHONY : src/http/routes_registery_test.i

# target to preprocess a source file
src/http/routes_registery_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/src/http/routes_registery_test.cpp.i
.PHONY : src/http/routes_registery_test.cpp.i

src/http/routes_registery_test.s: src/http/routes_registery_test.cpp.s
.PHONY : src/http/routes_registery_test.s

# target to generate assembly for a file
src/http/routes_registery_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_tests.dir/build.make CMakeFiles/web_server_tests.dir/src/http/routes_registery_test.cpp.s
.PHONY : src/http/routes_registery_test.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/utils/string_utils.o: src/utils/string_utils.cpp.o
.PHONY : src/utils/string_utils.o

# target to build an object file
src/utils/string_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/utils/string_utils.cpp.o
.PHONY : src/utils/string_utils.cpp.o

src/utils/string_utils.i: src/utils/string_utils.cpp.i
.PHONY : src/utils/string_utils.i

# target to preprocess a source file
src/utils/string_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/utils/string_utils.cpp.i
.PHONY : src/utils/string_utils.cpp.i

src/utils/string_utils.s: src/utils/string_utils.cpp.s
.PHONY : src/utils/string_utils.s

# target to generate assembly for a file
src/utils/string_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/web_server_lib.dir/build.make CMakeFiles/web_server_lib.dir/src/utils/string_utils.cpp.s
.PHONY : src/utils/string_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... event_loop"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... web_server"
	@echo "... web_server_lib"
	@echo "... web_server_tests"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/event_loop/event_loop_factory.o"
	@echo "... src/event_loop/event_loop_factory.i"
	@echo "... src/event_loop/event_loop_factory.s"
	@echo "... src/event_loop/macos_event_loop.o"
	@echo "... src/event_loop/macos_event_loop.i"
	@echo "... src/event_loop/macos_event_loop.s"
	@echo "... src/http/http_parser.o"
	@echo "... src/http/http_parser.i"
	@echo "... src/http/http_parser.s"
	@echo "... src/http/http_parser_test.o"
	@echo "... src/http/http_parser_test.i"
	@echo "... src/http/http_parser_test.s"
	@echo "... src/http/request.o"
	@echo "... src/http/request.i"
	@echo "... src/http/request.s"
	@echo "... src/http/response.o"
	@echo "... src/http/response.i"
	@echo "... src/http/response.s"
	@echo "... src/http/routes_registery.o"
	@echo "... src/http/routes_registery.i"
	@echo "... src/http/routes_registery.s"
	@echo "... src/http/routes_registery_test.o"
	@echo "... src/http/routes_registery_test.i"
	@echo "... src/http/routes_registery_test.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/utils/string_utils.o"
	@echo "... src/utils/string_utils.i"
	@echo "... src/utils/string_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

